"""
perf_sweep.py — Extension 1: Cycle-Accurate Performance Sweep
==============================================================
Supports two simulation backends:

  --simulator cpp       (default) C++ mini_sm_sim binary — fast, no tools needed
  --simulator modelsim  SystemVerilog RTL via ModelSim ASE — requires Intel ModelSim

Both backends run the same RAW-heavy workload (all warps: r0 + r1 -> r0) across
16 microarchitectural configurations (4 warp counts x 4 exec latencies) and
produce the same three plots:
  1. IPC vs Warp Count
  2. Stall Breakdown Heatmap
  3. Warp Efficiency vs Warp Count

Usage:
  python scripts/perf_sweep.py                          # C++ backend
  python scripts/perf_sweep.py --simulator modelsim     # RTL backend
  python scripts/perf_sweep.py --outdir results_cpp     # custom output dir
  python scripts/perf_sweep.py --cycles 5000            # cycles per point
"""

import subprocess
import itertools
import json
import argparse
import os
import textwrap
from pathlib import Path

try:
    import matplotlib.pyplot as plt
    import numpy as np
    HAS_MATPLOTLIB = True
except ImportError:
    HAS_MATPLOTLIB = False
    print("WARNING: matplotlib not installed — plots will be skipped.")

# ── Paths ──────────────────────────────────────────────────────────────────────

SCRIPT_DIR   = Path(__file__).resolve().parent
PROJECT_ROOT = SCRIPT_DIR.parent

# C++ backend
DEFAULT_SIM_BINARY = PROJECT_ROOT / "sim" / "build" / "mini_sm_sim.exe"
UCRT64_BIN         = Path("C:/msys64/ucrt64/bin")

# ModelSim backend
MODELSIM_PATH = Path("C:/intelFPGA/20.1/modelsim_ase/win32aloem")
VLIB = str(MODELSIM_PATH / "vlib")
VLOG = str(MODELSIM_PATH / "vlog")
VSIM = str(MODELSIM_PATH / "vsim")

RTL_FILES = [
    "rtl/core/simt_stack.sv",
    "rtl/core/simd_lane_alu.sv",
    "rtl/core/simt_alu_core.sv",
    "rtl/top/simt_alu.sv",
    "rtl/core/exec_pipe.sv",
    "rtl/control/warp_scheduler.sv",
    "rtl/control/wrap_table.sv",
    "rtl/control/scoreboard.sv",
    "rtl/control/pdom_ctrl.sv",
    "rtl/top/mini_sm_top.sv",
    "testbench/phase4/tb_perf_sweep.sv",
]

PKG_TEMPLATE = textwrap.dedent("""\
    // AUTO-GENERATED by perf_sweep.py — do not edit
    `ifndef SIMT_ALU_PKG_SV
    `define SIMT_ALU_PKG_SV
    package simt_alu_pkg;
        parameter int LANES        = 8;
        parameter int DATA_WIDTH   = 32;
        parameter int WARPS        = {warps};
        parameter int REGS         = 16;
        parameter int EXEC_LATENCY = {exec_latency};
        parameter int PC_W         = 16;
        parameter int PDOM_DEPTH   = 8;

        localparam int WARP_ID_W = $clog2(WARPS);
        localparam int REG_ID_W  = $clog2(REGS);

        typedef enum logic [1:0] {{
            WARP_READY   = 2'd0,
            WARP_STALLED = 2'd1
        }} warp_state_t;

        typedef struct packed {{
            logic [WARP_ID_W-1:0] warp_id;
            logic [REG_ID_W-1:0]  src0;
            logic [REG_ID_W-1:0]  src1;
            logic [REG_ID_W-1:0]  dst;
            logic                  has_dst;
            logic [2:0]            sel;
            logic [LANES-1:0]      lane_mask;
        }} instr_meta_t;

        typedef struct packed {{
            logic [PC_W-1:0]   reconv_pc;
            logic [LANES-1:0]  mask;
        }} pdom_entry_t;

    endpackage
    `endif // SIMT_ALU_PKG_SV
""")

# ── Sweep parameters ──────────────────────────────────────────────────────────

WARP_COUNTS   = [2, 4, 8, 16]
MEM_LATENCIES = [4, 8, 16, 32]

# ── Helpers ────────────────────────────────────────────────────────────────────

def make_env():
    """Prepend ucrt64 bin to PATH so the C++ binary finds its DLLs on Windows."""
    env = os.environ.copy()
    if UCRT64_BIN.exists():
        env["PATH"] = str(UCRT64_BIN) + os.pathsep + env.get("PATH", "")
    return env


def run_cmd(cmd: list, cwd: Path, timeout: int = 300) -> tuple[int, str]:
    result = subprocess.run(
        cmd, cwd=str(cwd),
        capture_output=True, text=True, timeout=timeout
    )
    return result.returncode, result.stdout + result.stderr


def parse_stats(filepath: Path) -> dict:
    stats = {}
    with open(filepath) as f:
        for line in f:
            line = line.strip()
            if "=" in line:
                key, val = line.split("=", 1)
                try:
                    stats[key.strip()] = int(val.strip())
                except ValueError:
                    try:
                        stats[key.strip()] = float(val.strip())
                    except ValueError:
                        pass

    cycles  = stats.get("cycles",        1)
    instrs  = stats.get("instructions",  0)
    issuing = stats.get("cycles_issuing", 0)

    stats["ipc"]             = instrs / cycles if cycles > 0 else 0.0
    stats["warp_efficiency"] = issuing / cycles * 100.0 if cycles > 0 else 0.0
    stats["stall_breakdown"] = {
        "data_hazard":    stats.get("stall_data",       0) / cycles * 100.0,
        "structural":     stats.get("stall_structural",  0) / cycles * 100.0,
        "memory_latency": stats.get("stall_memory",      0) / cycles * 100.0,
        "no_ready_warp":  stats.get("stall_no_warp",     0) / cycles * 100.0,
    }
    return stats


def _zero_stats():
    return {
        "ipc": 0.0, "warp_efficiency": 0.0,
        "stall_breakdown": {k: 0.0 for k in
            ["data_hazard", "structural", "memory_latency", "no_ready_warp"]}
    }

# ── C++ backend ───────────────────────────────────────────────────────────────

def run_cpp_point(binary: Path, warps: int, exec_latency: int,
                  cycles: int, stats_path: Path) -> tuple[int, str]:
    cmd = [
        str(binary),
        "--warps",        str(warps),
        "--exec-latency", str(exec_latency),
        "--cycles",       str(cycles),
        "--stats-file",   str(stats_path),
    ]
    return run_cmd(cmd, cwd=PROJECT_ROOT, timeout=60)


def run_sweep_cpp(binary: Path, output_dir: Path, cycles: int) -> dict:
    results = {}
    for warps, mem_lat in itertools.product(WARP_COUNTS, MEM_LATENCIES):
        stats_path = output_dir / f"stats_w{warps}_m{mem_lat}.txt"
        print(f"  warps={warps:2d}  exec_latency={mem_lat:3d}  ", end="", flush=True)

        rc, out = run_cpp_point(binary, warps, mem_lat, cycles, stats_path)

        if rc != 0 or not stats_path.exists():
            print(f"FAILED (rc={rc})")
            results[(warps, mem_lat)] = _zero_stats()
            continue

        try:
            stats = parse_stats(stats_path)
            results[(warps, mem_lat)] = stats
            print(f"IPC={stats['ipc']:.3f}  Eff={stats['warp_efficiency']:.1f}%")
        except Exception as e:
            print(f"PARSE FAILED: {e}")
            results[(warps, mem_lat)] = _zero_stats()

    return results

# ── ModelSim backend ──────────────────────────────────────────────────────────

def run_sweep_modelsim(output_dir: Path) -> dict:
    results = {}

    # Create work library once
    run_cmd([VLIB, "work"], cwd=PROJECT_ROOT)

    temp_pkg = output_dir / "simt_alu_pkg_sweep.sv"

    for warps, mem_lat in itertools.product(WARP_COUNTS, MEM_LATENCIES):
        stats_path = output_dir / f"stats_w{warps}_m{mem_lat}.txt"
        print(f"  warps={warps:2d}  exec_latency={mem_lat:3d}  ", end="", flush=True)

        # Write modified package for this config
        temp_pkg.write_text(PKG_TEMPLATE.format(warps=warps, exec_latency=mem_lat))

        # Compile package + RTL
        vlog_cmd = [VLOG, "-sv", str(temp_pkg)] + RTL_FILES
        rc, vlog_out = run_cmd(vlog_cmd, cwd=PROJECT_ROOT)
        if rc != 0 and "** Error" in vlog_out and "Errors: 0" not in vlog_out:
            print("COMPILE FAILED")
            results[(warps, mem_lat)] = _zero_stats()
            continue

        # Simulate
        vsim_cmd = [
            VSIM, "-c",
            "-do", "run -all; quit",
            f"+stats_file={stats_path}",
            "tb_perf_sweep",
        ]
        rc, vsim_out = run_cmd(vsim_cmd, cwd=PROJECT_ROOT, timeout=300)

        sim_errors = [l for l in vsim_out.splitlines()
                      if "** Error" in l and "vsim-3155" not in l]
        if sim_errors or not stats_path.exists():
            print("SIM FAILED")
            results[(warps, mem_lat)] = _zero_stats()
            continue

        try:
            stats = parse_stats(stats_path)
            results[(warps, mem_lat)] = stats
            print(f"IPC={stats['ipc']:.3f}  Eff={stats['warp_efficiency']:.1f}%")
        except Exception as e:
            print(f"PARSE FAILED: {e}")
            results[(warps, mem_lat)] = _zero_stats()

    return results

# ── Plots ─────────────────────────────────────────────────────────────────────

def plot_ipc_vs_warps(results: dict, output_dir: Path, title_suffix: str = ""):
    fig, ax = plt.subplots(figsize=(8, 5))
    colors = ["#2196F3", "#4CAF50", "#FF9800", "#F44336"]

    for idx, mem_lat in enumerate(MEM_LATENCIES):
        ipc_vals = [results[(w, mem_lat)]["ipc"] for w in WARP_COUNTS]
        theory   = [min(w, mem_lat + 1) / (mem_lat + 1) for w in WARP_COUNTS]
        ax.plot(WARP_COUNTS, ipc_vals,
                marker="o", linewidth=2, color=colors[idx],
                label=f"EL={mem_lat} (measured)")
        ax.plot(WARP_COUNTS, theory,
                linestyle="--", linewidth=1, color=colors[idx], alpha=0.4)

    ax.set_xlabel("Warp Count", fontsize=12)
    ax.set_ylabel("IPC (Instructions Per Cycle)", fontsize=12)
    ax.set_title(f"IPC vs Warp Count — Latency Hiding{title_suffix}", fontsize=13)
    ax.set_xticks(WARP_COUNTS)
    ax.legend(fontsize=9)
    ax.grid(True, alpha=0.3)
    fig.tight_layout()

    out = output_dir / "ipc_vs_warps.png"
    fig.savefig(out, dpi=150)
    print(f"  Saved: {out}")
    plt.close(fig)


def plot_stall_heatmap(results: dict, output_dir: Path, title_suffix: str = ""):
    mem_lat     = MEM_LATENCIES[2]
    stall_types = ["data_hazard", "structural", "memory_latency", "no_ready_warp"]
    labels      = ["Data Hazard", "Structural", "Mem Latency", "No Ready Warp"]

    data = np.array([
        [results[(w, mem_lat)]["stall_breakdown"].get(s, 0.0) for s in stall_types]
        for w in WARP_COUNTS
    ])

    fig, ax = plt.subplots(figsize=(8, 5))
    im = ax.imshow(data, cmap="YlOrRd", aspect="auto", vmin=0)
    ax.set_xticks(range(len(labels)))
    ax.set_xticklabels(labels, rotation=30, ha="right")
    ax.set_yticks(range(len(WARP_COUNTS)))
    ax.set_yticklabels([f"{w} warps" for w in WARP_COUNTS])
    ax.set_title(f"Stall Breakdown (% of cycles) — EL={mem_lat}{title_suffix}",
                 fontsize=12)

    for i in range(len(WARP_COUNTS)):
        for j in range(len(stall_types)):
            ax.text(j, i, f"{data[i, j]:.1f}%",
                    ha="center", va="center", fontsize=9,
                    color="black" if data[i, j] < 50 else "white")

    plt.colorbar(im, ax=ax, label="% of Total Cycles")
    fig.tight_layout()

    out = output_dir / "stall_breakdown_heatmap.png"
    fig.savefig(out, dpi=150)
    print(f"  Saved: {out}")
    plt.close(fig)


def plot_warp_efficiency(results: dict, output_dir: Path, title_suffix: str = ""):
    fig, ax = plt.subplots(figsize=(8, 5))
    colors = ["#2196F3", "#4CAF50", "#FF9800", "#F44336"]

    for idx, mem_lat in enumerate(MEM_LATENCIES):
        eff = [results[(w, mem_lat)]["warp_efficiency"] for w in WARP_COUNTS]
        ax.plot(WARP_COUNTS, eff,
                marker="s", linewidth=2, color=colors[idx],
                label=f"Exec Latency = {mem_lat} cycles")

    ax.set_xlabel("Warp Count", fontsize=12)
    ax.set_ylabel("Warp Efficiency (%)", fontsize=12)
    ax.set_title(f"Warp Efficiency vs Warp Count{title_suffix}", fontsize=13)
    ax.set_xticks(WARP_COUNTS)
    ax.set_ylim(0, 110)
    ax.axhline(y=100, color="gray", linestyle="--", alpha=0.5, label="100% ceiling")
    ax.legend(fontsize=9)
    ax.grid(True, alpha=0.3)
    fig.tight_layout()

    out = output_dir / "warp_efficiency.png"
    fig.savefig(out, dpi=150)
    print(f"  Saved: {out}")
    plt.close(fig)

# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="Mini-SM performance sweep (C++ or ModelSim backend)")
    parser.add_argument("--simulator", choices=["cpp", "modelsim"], default="cpp",
                        help="Simulation backend (default: cpp)")
    parser.add_argument("--outdir",   default=None,
                        help="Output directory (default: perf_results_cpp or perf_results_rtl)")
    parser.add_argument("--cycles",   type=int, default=2000,
                        help="Simulation cycles per point, C++ backend only (default: 2000)")
    parser.add_argument("--sim-binary", default=str(DEFAULT_SIM_BINARY),
                        help="Path to mini_sm_sim binary (C++ backend only)")
    args = parser.parse_args()

    # Default output dir based on backend
    if args.outdir is None:
        args.outdir = "perf_results_cpp" if args.simulator == "cpp" else "perf_results_rtl"

    output_dir = PROJECT_ROOT / args.outdir
    output_dir.mkdir(exist_ok=True)

    title_suffix = " (C++ model)" if args.simulator == "cpp" else " (RTL — ModelSim)"

    print(f"=== Mini-SM Performance Sweep ({args.simulator.upper()} backend) ===")
    print(f"  Warp counts    : {WARP_COUNTS}")
    print(f"  Exec latencies : {MEM_LATENCIES}")
    print(f"  Output dir     : {output_dir}")

    if args.simulator == "cpp":
        binary = Path(args.sim_binary)
        if not binary.exists():
            print(f"\nERROR: binary not found: {binary}")
            print("  Build first: cd sim && cmake -B build -G \"MinGW Makefiles\" && cmake --build build")
            return 1
        print(f"  Binary         : {binary}")
        print(f"  Cycles/point   : {args.cycles}")
        print()
        results = run_sweep_cpp(binary, output_dir, args.cycles)
    else:
        if not MODELSIM_PATH.exists():
            print(f"\nERROR: ModelSim not found at {MODELSIM_PATH}")
            print("  Install Intel ModelSim ASE or update MODELSIM_PATH in this script.")
            return 1
        print(f"  ModelSim       : {MODELSIM_PATH}")
        print()
        results = run_sweep_modelsim(output_dir)

    # Save raw results
    serializable = {f"w{w}_m{m}": v for (w, m), v in results.items()}
    with open(output_dir / "raw_results.json", "w") as f:
        json.dump(serializable, f, indent=2)
    print(f"\n  Raw results saved to {output_dir / 'raw_results.json'}")

    if HAS_MATPLOTLIB:
        print("\nGenerating plots...")
        plot_ipc_vs_warps(results, output_dir, title_suffix)
        plot_stall_heatmap(results, output_dir, title_suffix)
        plot_warp_efficiency(results, output_dir, title_suffix)
        print(f"\nAll plots saved to: {output_dir}/")
    else:
        print("\nSkipping plots — install with: pip install matplotlib numpy")

    # IPC summary table
    print("\n--- IPC Summary Table ---")
    header = f"{'Warps':>6}" + "".join(f"  EL={m:>3}" for m in MEM_LATENCIES)
    print(header)
    for w in WARP_COUNTS:
        row = f"{w:>6}"
        for m in MEM_LATENCIES:
            ipc = results.get((w, m), {}).get("ipc", 0.0)
            row += f"   {ipc:.3f}"
        print(row)

    return 0

if __name__ == "__main__":
    raise SystemExit(main())
